# Generated by Django 3.1.4 on 2021-01-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_default_phone_number',
            new_name='default_phone_number',
        ),
    ]
